version: '3'
services:
  web:
    build: 
        context: ./images/app
    ports:
      - "8888:8080"
    networks:
      - docker-practice-net
    depends_on:
      - postgres
      - redis 
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    ports:
      - "5432:5432"
    networks:
      - docker-practice-net 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - docker-practice-net
networks:
  docker-practice-net:
    driver: bridge
